services:
  - type: web
    name: compensey-frontend
    runtime: node
    buildCommand: npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://compensey-backend.onrender.com
